config/routes.rb
Rails.application.routes.draw do
  root to: 'maps#new'

  resources :maps, only: [:show, :new, :update]

  namespace :admin do
    root to: 'words#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  serialize :tiles, JSON

  def tiles
    super || []
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < AdminController
  def index
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def new
  end

  def show
    @map = Map.find(params[:id])
  end

  def update
    @map = Map.find(params[:id])

    @map.update(map_params)
  end

  private

  def map_params
    params.require(:map).permit(tiles: [ :q, :r ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/words/index.html.erb
WORDS

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cartographer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application' %>
  </head>

  <body>
    <canvas id="map"></canvas>

    <%= javascript_include_tag 'vendor', 'application' %>

    <%= yield %>
  </body>
</html>

app/views/maps/new.html.erb
<div class="hidden">
  GENERAL PURPOSE DATA
</div>

<script type="text/javascript">

var canvas = document.getElementById('map');
var data = [{ q: 0, r: 0 }];

Tapestry.sizeTo(window, canvas);
Cartographer.setMap(data);
Cartographer.draw(data, canvas);

var mc = new Hammer.Manager(canvas);

mc.add(new Hammer.Tap());
mc.on("tap", Cartographer.plotSurroundings(canvas));

mc.add(new Hammer.Pan());
mc.on("pan", Cartographer.pan(canvas));

</script>

app/views/maps/show.html.erb
<div class="hidden">
  GENERAL PURPOSE DATA
</div>

<script type="text/javascript">

var canvas = document.getElementById('map');
var map = JSON.parse('<%= @map.tiles.to_json.html_safe %>');

Tapestry.sizeTo(window, canvas);
Cartographer.setMap(map);
Cartographer.draw(map, canvas);

var mc = new Hammer.Manager(canvas);

mc.add(new Hammer.Tap());
mc.on("tap", Cartographer.plotSurroundings(canvas, '<%= map_url(@map) %>'));

mc.add(new Hammer.Pan());
mc.on("pan", Cartographer.pan(canvas));

</script>

app/views/maps/update.html.erb
<%= @data.inspect %>